---
excludes:
  scopes:
  - pattern: "testDependencies"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only. Not part of released artifacts."
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only. Not part of released artifacts"