snmp:
  mibs:
    dir: "/work/mibs/pysnmp"
    load_list: "lookups/mibs_list.csv"
    mibs_path: "/work/mibs"
mongo:
  oid:
    database: "snmp_traps"
    collection: "oids"
  mib:
    database: "files"
    collection: "mib_files"
