# Copyright 2021 Splunk Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

profiles:
  Walk:
    #This results in walking about 4 times per day but avoids having the work trigger at the same time daily
    frequency: 22000
    patterns:
      - "^."
    varBinds:
      - "1.3.6.1.2.1.2.*"
  #Uptime is very important we will check uptime once per minute
  BaseUpTime:
    frequency: 60
    patterns:
      - "^.*"
    varBinds:
      - ["SNMPv2-MIB", "sysUpTime", 0]
  BaseDeviceData:
    frequency: 600
    patterns:
      - "^.*"
    varBinds:
      # Syntax: [ "MIB-Files", "MIB object name" "MIB index number"]
      - ["SNMPv2-MIB", "sysDescr"]
      - ["SNMPv2-MIB", "sysName"]
      - ["SNMPv2-MIB", "sysObjectID"]
      - ["SNMPv2-MIB", "sysContact"]
      - ["SNMPv2-MIB", "sysLocation"]
  BaseIFMeta:
    frequency: 300
    patterns:
      - "^.*"
    varBinds:
      - ["IF-MIB", "ifType", "*"]
      - ["IF-MIB", "ifMtu", "*"]
      - ["IF-MIB", "ifSpeed", "*"]
      - ["IF-MIB", "ifAdminStatus", "*"]
  BaseIF:
    frequency: 30
    patterns:
      - "^.*"
    varBinds:
      # Syntax: [ "MIB-Files", "MIB object name" "MIB index number"]
      - ["IF-MIB", "ifInDiscards", "*"]
      - ["IF-MIB", "ifInErrors", "*"]
      - ["IF-MIB", "ifInNUcastPkts", "*"]
      - ["IF-MIB", "ifInOctets", "*"]
      - ["IF-MIB", "ifInUcastPkts", "*"]
      - ["IF-MIB", "ifInUnknownProtos", "*"]
      - ["IF-MIB", "ifOutDiscards", "*"]
      - ["IF-MIB", "ifOutErrors", "*"]
      - ["IF-MIB", "ifOutNUcastPkts", "*"]
      - ["IF-MIB", "ifOutOctets", "*"]
      - ["IF-MIB", "ifOutQLen", "*"]
      - ["IF-MIB", "ifOutUcastPkts", "*"]
      - ["IF-MIB", "ifOperStatus", "*"]
